name: Deploy Personal Website
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Docker Hub访问令牌

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/northminzu-personal-site:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_SERVER }}        # 服务器IP
          username: ${{ secrets.HOST_USER_NAME }}  # 服务器用户名（如ubuntu）
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }} # SSH私钥
          port: 22
          debug: ture
          script: |
            cd /home/ubuntu/website
            docker compose down
            docker compose pull
            docker compose up -d